### ISSUE TITLE
cannot access a scoped thread local variable without calling `set` first

### ISSUE THREAD

**Issue by tabokie** [tokio-rs/loom#192]
I tried to use loom but the test failed at Mutex initialization with panic "cannot access a scoped thread local variable without calling `set` first". I've looked through related issues but they don't seem to apply to my case.

I ran my test with `RUSTFLAGS="--cfg loom" RUST_BACKTRACE=1 cargo test --package file_system -- --nocapture test_condvar`

```rust
#[cfg(test)]
mod tests {
    use super::super::time_util;
    use super::*;
    use loom::sync::atomic::{AtomicUsize, Ordering};
    use loom::sync::Arc;
    use loom::thread;

    use test::Bencher;

    #[test]
    fn test_condvar() {
        let long_timeout_millis = 1000 * 100;
        let short_timeout_millis = 1;
        let total_waits = 50;

        let mu = Arc::new(Mutex::new(()));  // panic
        /* rest of the test */
    }
}
```

backtrace:
```
running 1 test
thread 'condvar::tests::test_condvar' panicked at 'cannot access a scoped thread local variable without calling `set` first', /home/tabokie/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:168:9
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/std/src/panicking.rs:505:12
   1: scoped_tls::ScopedKey<T>::with
             at /home/tabokie/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:168:9
   2: loom::rt::scheduler::Scheduler::with_execution
             at /home/tabokie/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.4.0/src/rt/scheduler.rs:48:9
   3: loom::rt::execution
             at /home/tabokie/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.4.0/src/rt/mod.rs:138:5
   4: loom::rt::mutex::Mutex::new
             at /home/tabokie/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.4.0/src/rt/mutex.rs:29:9
   5: loom::sync::mutex::Mutex<T>::new
             at /home/tabokie/.cargo/registry/src/github.com-1ecc6299db9ec823/loom-0.4.0/src/sync/mutex.rs:25:21
   6: file_system::condvar::tests::test_condvar
             at ./src/condvar.rs:224:27
   7: file_system::condvar::tests::test_condvar::{{closure}}
             at ./src/condvar.rs:219:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/b1496c6e606dd908dd651ac2cce89815e10d7fc5/library/core/src/ops/function.rs:227:5
```

**Comment by tabokie** [comment]
Sorry, I didn't notice the `model` entry point. Closing this now.
